server.port=7443
spring.application.name=auth-server

server.ssl.enabled=true
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.3
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:certs/authz-keystore.p12
server.ssl.key-store-password=password
server.ssl.key-alias=authz
server.ssl.trust-store-type=PKCS12
server.ssl.trust-store=classpath:certs/authz-truststore.p12
server.ssl.trust-store-password=password

spring.mail.port=1025
spring.mail.host=localhost

spring.datasource.url=jdbc:postgresql://localhost:5432/workouts
spring.datasource.username=user
spring.datasource.password=password