server.port=9443
spring.application.name=gateway

server.ssl.enabled=true
server.ssl.key-store=classpath:certs/gateway-keystore.p12
server.ssl.key-store-password=password

spring.security.oauth2.client.registration.gateway-client-oidc.client-id=gateway-client
spring.security.oauth2.client.registration.gateway-client-oidc.client-secret=secret
spring.security.oauth2.client.registration.gateway-client-oidc.scope=workouts:read
spring.security.oauth2.client.registration.gateway-client-oidc.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gateway-client-oidc.redirect-uri={baseUrl}/login/oauth2/code/gateway-client-oidc
spring.security.oauth2.client.provider.auth-server-provider.authorization-uri=https://authz.127.0.0.1.nip.io:7443/oauth2/authorize
spring.security.oauth2.client.provider.auth-server-provider.user-info-uri=http://localhost:7080/user
spring.security.oauth2.client.provider.auth-server-provider.token-uri=http://localhost:7080/oauth2/token
spring.security.oauth2.client.provider.auth-server-provider.jwk-set-uri=http://localhost:7080/oauth2/jwks
spring.security.oauth2.client.provider.auth-server-provider.user-name-attribute=sub
spring.security.oauth2.client.registration.gateway-client-oidc.provider=auth-server-provider
