server.port=8443
spring.application.name=api

server.ssl.client-auth=need
server.ssl.enabled=true
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.3
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:certs/api-keystore.p12
server.ssl.key-store-password=password
server.ssl.key-alias=api
server.ssl.trust-store-type=PKCS12
server.ssl.trust-store=classpath:certs/api-truststore.p12
server.ssl.trust-store-password=password
