services:
  maildev:
    image: maildev/maildev:2.1.0
    ports:
      - "1080:1080"
      - "1025:1025"
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/db/data:/var/lib/postgresql/data
      - ${PWD}/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=workouts